version: '3.8'

services:
  ovn-dashboard:
    build:
      context: .
      dockerfile: dockerfile
      network: host
    container_name: ovn_dashboard_web
    ports:
      - "3089:3089"
    environment:
      - NODE_ENV=production
      - PORT=3089
      - NEXT_PUBLIC_API_URL=http://localhost:8001
    restart: unless-stopped
    #    networks:
    #      - ovn_network
    network_mode: "host"

#networks:
#  ovn_network:
#    driver: bridge
